### ISSUE TITLE
IdExtenso's main folder has not been found. 

### ISSUE THREAD

**Issue by RyanFungJM** [indiscripts/IdExtenso#1]
<img width="532" alt="屏幕快照 2019-04-21 上午1 15 01" src="https://user-images.githubusercontent.com/8000484/56460276-d89d9a00-63d2-11e9-9651-0a9202e836fb.png">
IdExtenso's main folder has not been found. Do you want to continue?

**Comment by indiscripts** [comment]
Hi RyanFung,
This message warns you that `ScriptTemplate.jsx` is running in an environment where IdExtenso source files are missing — or, at least, not available at their expected location.

You can still create a template anyway. But of course IdExtenso is required behind the scene to get your script working at dev stage.

If you moved the framework at a specific location, you can specify its path from `Template and Folders` > `IdExtenso path`, as shown below.

![IdexPath](https://user-images.githubusercontent.com/6134238/56479368-6a7dd380-64b5-11e9-8847-29b91f9f314b.png)

Thanks for your feedback.

**Comment by RyanFungJM** [comment]
thanks, I get it.
