### ISSUE TITLE
Unicode characters in Google Docs

### ISSUE THREAD

**Issue by CharlieNH** [indiscripts/IdExtenso#3]
Hi, Marc. Thanks for taking a look at this for me.

You can put the attached script in the /IdExtenso-master/ folder.

You'll also need to put the attached .gdoc file on your Desktop. It's formatted in Google's "Backup and Sync" format (Windows) and just points to the test document I created for you, which you can examine here: https://docs.google.com/document/d/1kqrEmyUzKlVGY3Q_Zj1lcsqXstOSQAYKhWkLU_ndkX8/edit

(I had to add .txt to each filename to be able to upload it to GitHub.) 

You'll need to open any InDesign document to serve as a test bed. The script will create a new page on which to put the Google Doc file.

When you run the script, it will ask you to pick a file ... pick the .gdoc file on your Desktop.

It will take about 30 seconds for the Google Doc to appear in the InDesign document.

I hope this helps! I'll be happy to help you on this in any way I can.

Charlie

[Test Harness for Marc.jsx.txt](https://github.com/indiscripts/IdExtenso/files/5922072/Test.Harness.for.Marc.jsx.txt)
[Large Google Doc for testing - BHTNH.gdoc.txt](https://github.com/indiscripts/IdExtenso/files/5922074/Large.Google.Doc.for.testing.-.BHTNH.gdoc.txt)

**Comment by indiscripts** [comment]
Hi Charlie,

I've tested the below script. It is based on your original code from which I've removed Unicode post-processing to see how data arrive from `$$.Web()`.

[003_UnicodeCharactersGoogleDocs.zip](https://github.com/indiscripts/IdExtenso/files/5926576/003_UnicodeCharactersGoogleDocs.zip)

but it can't see weird characters in the result:

![NoIssue](https://user-images.githubusercontent.com/6134238/106912331-35cb2280-6703-11eb-9485-bc5c6a8c2f1a.png)

Are you sure the Google doc you've prepared for my test actually contains special characters (?) All seems to work fine here…

_(Tested in InDesign CC 2021 / Win10.)_

**Comment by indiscripts** [comment]
@CharlieNH 

**Important:** Make sure you use the most recent version of the [Web module](https://github.com/indiscripts/IdExtenso/blob/master/etc/%24%24.Web.jsxlib) (last update is `210203`.)

**Comment by CharlieNH** [comment]
I'm installing the latest Web module and will try to test it later today.

I apologize for not having made the sample document more "tester friendly." I have now stripped everything out of the sample document except for a couple of sentences that contain typographer's apostrophes; left and right typographer's double quotes; a couple of n-dashes; and an ellipsis. 

You should be able to simply run your script again, because the .gdoc link should still point to the test file, and the test file is still in the same spot ... it's just much shorter.

I'll try to test yesterday's module soon ... maybe it fixes the problem. 

And thanks for the huge re-write of my code. I'm going to learn a TON about good JS coding by examining it very carefully!

Thanks for your help!

**Comment by indiscripts** [comment]
@CharlieNH 

> I have now stripped everything out of the sample document except
> for a couple of sentences that contain typographer's apostrophes;
> left and right typographer's double quotes; a couple of n-dashes; and
> an ellipsis.

Seems to work for me:

![image](https://user-images.githubusercontent.com/6134238/107034072-7df74d00-67b6-11eb-8b15-cec4ebce930b.png)

**Comment by CharlieNH** [comment]
Perfect! That's great news. I'll try to get the new version installed and
tested this weekend, and hopefully I'll have the same good results.

Either way, I'll report back to you as soon as I can.

In the meantime, I have a sidebar question for you, if you don't mind. I'd
like to become a much more advanced JS coder, at least to the point where I
can read and understand some of the advanced structures and syntax that you
use. Can you recommend a good book that covers JS that deeply? Or a
website? Or do I have to start digging into the ECMAScript specification?

Thanks, Marc! I hope to get back to you with good news soon.

Charlie

**Comment by indiscripts** [comment]
@CharlieNH 

* I would recommend https://eloquentjavascript.net, a very good guide if you want to enter JS programming with language and root structures in mind. And of course the ECMAScript (262) specification.

* That said, Adobe ExtendScript for InDesign is a particular JS dialect with specific issues and oddities (!) To my knowledge there is no _advanced_ documentation on it. Many obscure facts are reported in IdExtenso's comments (see the BACKGROUND and/or NOTICE parts in my code). Dealing with that stuff requires practice but this won't help you become a “more advanced JS coder”. (ExtendScript does not even comply with the present JavaScript standard!)

* Regarding coding style, mine is considered esoteric by many of my colleagues. It perfectly fits my needs—and the purpose of IdExtenso as a framework—but I definitely won't propose it as a good model for improving your JS skills. More academic resources are available online, for example https://courseduck.com/programming/javascript/ which sounds great.

**Comment by CharlieNH** [comment]
Thanks! That's exactly the kind of guidance I was looking for.

And as for "esoteric," I salute you!

Charlie

**Comment by CharlieNH** [comment]
OK, I've finally found time to test the 210203 update of Web.jsxlib and I agree with your findings, Marc -- it seems to handle the Unicode characters perfectly.

Thanks very much for all your help on this, Marc, and your sage advice. Case closed!

Charlie
